# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('AirSimConnect-example', ['AirSimConnect'])
    obj.source = 'AirSimConnect-example.cc'

